### ISSUE TITLE
 Due to triggering sensitive operations, it was blocked by antivirus software.

### ISSUE THREAD

**Issue by srackhall** [M1ndo/Neptune#4]
![image](https://github.com/M1ndo/Neptune/assets/65339064/ab144116-95af-49a4-affa-3dc663d3ab3c)

> Due to triggering sensitive operations, it was blocked by antivirus software.

Then I couldn't close Neptune. even in Task Manager, I couldn't end the process (until I restarted my computer to end this nightmare...)

**Comment by M1ndo** [comment]
Hello, like i've mentioned in the README.md the windows exe is not signed so it will likely get flagged.

The only reason your AV blocked Neptune, is because Neptune attempted to download keyboard sounds when it was started for the first time check the [code](https://github.com/M1ndo/Neptune/blob/main/pkg/ui/mainwindow.go#L92) so when you AV blocked it, it didn't continue downloading and likely crashed.

If you could recompile it with go using  ```go build -ldflags="-s -w"``` it won't be blocked by your AV

**Comment by srackhall** [comment]
Hello, thank you for your patient answer. I apologize for not carefully reading the README.md document myself.


However, I mentioned that when a crash triggers a restart, it is indeed a problem that it cannot be shut down by killing the process. So much so that I had to restart my computer to solve it (of course, closing antivirus software may allow it to execute normally, and it can be closed normally).


Due to certain reasons, I am unable to close or whitelist antivirus software, so I have decided to try recompiling it using the go language as you mentioned.
